### ISSUE TITLE
ModuleNotFoundError: No module named 'pip._vendor.progress' INSTALL FAILED

### ISSUE THREAD

**Issue by luismroal** [freewillfx-azenqos/azenqos_qgis_plugin#1]
Hi! I am trying to load the plugin but I am not successful in the process, I get an error message and I honestly do not know what could be happening, could you help me?

This is the error log: 

=== AZENQOS log file analysis QGIS plugin installer ===
- Please make sure QGIS is closed first.
- Any existing Azenqos plugins would get deleted and replaced
== Finding local QGIS installation folder...
Found QGIS InstallPath: C:\Program Files\QGIS 3.16
== Preparing QGIS16 cmd env...
== Installing required python packages into QGIS's python env...
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\LuisMiguelRosas\AppData\Roaming\Python\Python37\site-packages\pip\__main__.py", line 23, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "C:\Users\LuisMiguelRosas\AppData\Roaming\Python\Python37\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\LuisMiguelRosas\AppData\Roaming\Python\Python37\site-packages\pip\_internal\cli\autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\LuisMiguelRosas\AppData\Roaming\Python\Python37\site-packages\pip\_internal\cli\main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "C:\Users\LuisMiguelRosas\AppData\Roaming\Python\Python37\site-packages\pip\_internal\cli\cmdoptions.py", line 24, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "C:\Users\LuisMiguelRosas\AppData\Roaming\Python\Python37\site-packages\pip\_internal\cli\progress_bars.py", line 8, in <module>
    from pip._vendor.progress.bar import Bar, FillingCirclesBar, IncrementalBar
ModuleNotFoundError: No module named 'pip._vendor.progress'
INSTALL FAILED
Presione una tecla para continuar . . .

**Comment by luismroal** [comment]
I was making a mistake

**Comment by ykasidit** [comment]
Glad to hear that you resolved the issue :-)
